---
- name: Certificates directory
  ansible.builtin.file:
    path: "{{ certificates_dir }}"
    state: directory
    mode: '0775'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Copy default Certificate
  ansible.builtin.copy:
    src: certificates/default.rdp-tls.crt
    dest: "{{ certificates_dir }}/rdp-tls.crt"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0664'

- name: Copy default Key
  ansible.builtin.copy:
    src: certificates/default.rdp-tls.key
    dest: "{{ certificates_dir }}/rdp-tls.key"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0664'

